dist: xenial # required for Python >= 3.7
language: python
cache: pip
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - pip install pycodestyle coverage codecov
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2.7* ]]; then pip install mock; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.5* ]]; then pip install aiohttp asynctest; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.6* ]]; then pip install aiohttp asynctest; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.7* ]]; then pip install aiohttp asynctest; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.8* ]]; then pip install aiohttp asynctest; fi
install:
  - pip install virtualenv --upgrade
  - make install
  - make test-install
script:
  - pycodestyle --exclude=venv
  - coverage run -m unittest discover -p "test_*.py" -v
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.5* ]]; then coverage run -m unittest discover -p "async_test_*.py" -v; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.6* ]]; then coverage run -m unittest discover -p "async_test_*.py" -v; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.7* ]]; then coverage run -m unittest discover -p "async_test_*.py" -v; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.8* ]]; then coverage run -m unittest discover -p "async_test_*.py" -v; fi
after_script:
  - codecov
  - make test
  - coverage run tests/test_unit.py
after_success:
  - codecov
deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_TEST_RESULT = 0"
    tags: true
    python: '3.6'
